### ISSUE TITLE
[Feature] Ratings Form and Analytics Dashboard

### ISSUE THREAD

**Issue by jakezych** [CMU-313/fall22-hw3-jabby#1]
**Description:**
This feature is broken up into two major sub-features. The first major sub-feature will be a form that allows reviewers to score applicants (represented by a single document) on three different criteria: technical skills, interpersonal skills, and fit. These will be scored on a scale of 1 to 10. This will be accessed by a new button under the Share button on the page that pops up after clicking on a document from the left side list. The second major feature will be an Analytics tab next to the Activity tab accessible on the same page as the button. Clicking on this tab will open a "dashboard" showing the average rating the applicant received for each category. This will also show an overall rating taken as an average of the average they received in each category. Additionally, the dashboard will show what percentage of reviewers submitted a review taken out of the total number of users in the system acting as a check to see if the applicant has been fully reviewed or not. 

These are the intended features we intend to tackle for our first sprint. Future improvements include: other forms of aggregating data with the ability to switch between them in the frontend and allowing users to have finer grain ratings by inputting their own number rather than selecting from a dropdown. This would require implementing input validation. 

**List of Changes:**

- Frontend:
  - (Asyer) Creating button that opens form 
  - (Asyer) Creating form that takes in ratings across different categories 
  - Drop down menu for each with a rating 1 through 10 
    - Categories: 
      - Technical Skills 
      - Interpersonal Skills 
      - Fit 
  - (Brandon) Creating a new tab called “Analytics” next to Activity that opens a new page 
  - (Brandon) Creating a dashboard under this tab that shows average ratings across reviewers for each category and an overall score 
    - Dashboard should also show the percentage of reviewers who reviewed it (relative to total number) 
- Middleware:
  - (Jake) POST request API that is called upon form submission 	
    - Takes in as input:
      - All of the ratings assigned 
      - The id of the document it was called on
      - The id of the user who rated it 
    - Saves the ratings the user gave into the backend under each of the documents’s ratings columns 
  - (Richard/Annie) GET request API that is called when the analytics tab is opened 
    - Returns the average rating for each category of that document 
    - Returns an overall average rating for the document (student)
  - (Richard/Annie) GET request API that is called when the analytics tab is opened 
    - Returns the percentage of users who reviewed the document relative to the total number of users 
- Backend:
  - (Richard/Annie) Create a column (in the Documents table) for each rating on the form
    - Technical Skills
    - Interpersonal Skills
    - Fit 
  - (Richard/Annie) Update the DTO and DAO SQL queries to extract ratings from the columns and populate the objects 

**Dependencies:**
The frontend can be worked on in parallel with the other components. 

The middleware is dependent upon the backend being complete to test; however, implementation can begin if names of columns and variables are agreed upon prior.

The frontend cannot be tested end to end until the middleware and backend is complete. 

The backend has no dependencies and will be completed first. 

**Acceptance Criteria:**
After this features is implemented, any user with write permissions for a particular document should be able to give it a score of 1-10 in three criteria mentioned above and submit using a form accessible through a button. Opening the analytics tab should correctly display the average rating the document has received across all reviewers. In addition to this, the tab should display the average of these average as an overall score of the document as well as the percentage of reviewers who have reviewed the document.

**Comment by awutis** [comment]
Feature complete - refer to README.md for documentation!
