### ISSUE TITLE
[Sub-Feature] Update SQL queries to extract ratings from columns and populate objects

### ISSUE THREAD

**Issue by awutis** [CMU-313/fall22-hw3-jabby#11]
**Description:**
After the columns in the Documents table have been updated, we also need to update the corresponding SQL queries that allows the middleware to extract ratings from columns and populate objects. 

**Acceptance Criteria:**
The project should still be able to build and add unit tests if necessary. 

**Dependencies:**
This should be completed after the database successfully updates. 

**Estimated Effort:**
If nothing goes wrong, this should be completed in < 1 day.

**Comment by jakezych** [comment]
Already implemented in issue #10
