### ISSUE TITLE
[Debugging] Percentage reviews always 1 or 0

### ISSUE THREAD

**Issue by awutis** [CMU-313/fall22-hw3-jabby#22]
**Description:**
Under the analytics tab, after a document has been reviewed by ≥1 user, the percentage review displays 1% even in the case where there are only 2 active users

**Suggestion Solution:** 
We believe this is caused by Math.round issues (rounding to the nearest integer), and our API that gets the percent review returns a decimal

**Estimated Effort:**
30min - 1hr

**Comment by jakezych** [comment]
Working on the fix now!
